classDiagram
class HexxagonGame {
    +test: String
    +play()
}

class Board

class Field {
    +state: FieldState
}

class FieldState {
    <<enumeration>>
    BLOCKED
    FREE
    PLAYERONE
    PLAYERTWO
}

class Player

class Server

class Screen

class MainMenu

class GameScreen

class GameController

Field "61" --* "1" Board

MainMenu --|> Screen

GameScreen --|> Screen

GameController "1" o-- "1" HexxagonGame

GameController "1" o-- "1" GameScreen

GameController <--> Server: communicate

class MenuController

MenuController "1" o-- "1" MainMenu

MenuController --> Server: connect

Board "1" --o "1" HexxagonGame

Player "2" --o "1" HexxagonGame
